export const user = [
  {
    name: "rakshit",
    age: "19",
    totalOrders: 12,
    email: "21bec085@iiitdmj.ac.in",
    phoneNumber: "9967334082",
    products: {
      productOrders: [
        {
          orderID: "ORD001",
          productID: "PROD001",
          productName: "Wireless Headphones",
          category: "Electronics",
          quantity: 1,
          price: 59.99,
          orderDate: "2023-08-20",
          status: "Delivered",
        },
        {
          orderID: "ORD002",
          productID: "PROD002",
          productName: "Bluetooth Speaker",
          category: "Electronics",
          quantity: 2,
          price: 29.99,
          orderDate: "2023-10-05",
          status: "Delivered",
        },
        {
          orderID: "ORD003",
          productID: "PROD003",
          productName: "Running Shoes",
          category: "Sports",
          quantity: 1,
          price: 89.99,
          orderDate: "2023-11-12",
          status: "Shipped",
        },
        {
          orderID: "ORD004",
          productID: "PROD004",
          productName: "Hiking Backpack",
          category: "Outdoor",
          quantity: 1,
          price: 79.99,
          orderDate: "2023-12-18",
          status: "Shipped",
        },
        {
          orderID: "ORD005",
          productID: "PROD005",
          productName: "Coffee Maker",
          category: "Home & Kitchen",
          quantity: 1,
          price: 49.99,
          orderDate: "2024-02-02",
          status: "Delivered",
        },
        {
          orderID: "ORD006",
          productID: "PROD006",
          productName: "Gaming Mouse",
          category: "Electronics",
          quantity: 1,
          price: 39.99,
          orderDate: "2024-03-15",
          status: "Delivered",
        },
        {
          orderID: "ORD007",
          productID: "PROD007",
          productName: "Yoga Mat",
          category: "Sports",
          quantity: 1,
          price: 29.99,
          orderDate: "2024-04-25",
          status: "Shipped",
        },
        {
          orderID: "ORD008",
          productID: "PROD008",
          productName: "Bluetooth Earbuds",
          category: "Electronics",
          quantity: 1,
          price: 69.99,
          orderDate: "2024-05-10",
          status: "Delivered",
        },
        {
          orderID: "ORD009",
          productID: "PROD009",
          productName: "Camping Tent",
          category: "Outdoor",
          quantity: 1,
          price: 149.99,
          orderDate: "2024-05-30",
          status: "Shipped",
        },
        {
          orderID: "ORD010",
          productID: "PROD010",
          productName: "Fitness Tracker",
          category: "Fitness",
          quantity: 1,
          price: 79.99,
          orderDate: "2024-06-05",
          status: "Delivered",
        },
        {
          orderID: "ORD011",
          productID: "PROD011",
          productName: "Portable Charger",
          category: "Electronics",
          quantity: 1,
          price: 19.99,
          orderDate: "2024-06-10",
          status: "Delivered",
        },
        {
          orderID: "ORD012",
          productID: "PROD012",
          productName: "Cookware Set",
          category: "Home & Kitchen",
          quantity: 1,
          price: 99.99,
          orderDate: "2024-06-15",
          status: "Shipped",
        },
      ],
    },
    bankingTransactions: {
      bankingTransactions: [
        {
          transactionID: "TXN001",
          orderID: "ORD001",
          amount: -59.99,
          transactionDate: "2023-08-20",
          description: "Wireless Headphones Purchase",
        },
        {
          transactionID: "TXN002",
          orderID: "ORD002",
          amount: -59.98,
          transactionDate: "2023-10-05",
          description: "Bluetooth Speaker Purchase",
        },
        {
          transactionID: "TXN003",
          orderID: "ORD003",
          amount: -89.99,
          transactionDate: "2023-11-12",
          description: "Running Shoes Purchase",
        },
        {
          transactionID: "TXN004",
          orderID: "ORD004",
          amount: -79.99,
          transactionDate: "2023-12-18",
          description: "Hiking Backpack Purchase",
        },
        {
          transactionID: "TXN005",
          orderID: "ORD005",
          amount: -49.99,
          transactionDate: "2024-02-02",
          description: "Coffee Maker Purchase",
        },
        {
          transactionID: "TXN006",
          orderID: "ORD006",
          amount: -39.99,
          transactionDate: "2024-03-15",
          description: "Gaming Mouse Purchase",
        },
        {
          transactionID: "TXN007",
          orderID: "ORD007",
          amount: -29.99,
          transactionDate: "2024-04-25",
          description: "Yoga Mat Purchase",
        },
        {
          transactionID: "TXN008",
          orderID: "ORD008",
          amount: -69.99,
          transactionDate: "2024-05-10",
          description: "Bluetooth Earbuds Purchase",
        },
        {
          transactionID: "TXN009",
          orderID: "ORD009",
          amount: -149.99,
          transactionDate: "2024-05-30",
          description: "Camping Tent Purchase",
        },
        {
          transactionID: "TXN010",
          orderID: "ORD010",
          amount: -79.99,
          transactionDate: "2024-06-05",
          description: "Fitness Tracker Purchase",
        },
        {
          transactionID: "TXN011",
          orderID: "ORD011",
          amount: -19.99,
          transactionDate: "2024-06-10",
          description: "Portable Charger Purchase",
        },
        {
          transactionID: "TXN012",
          orderID: "ORD012",
          amount: -99.99,
          transactionDate: "2024-06-15",
          description: "Cookware Set Purchase",
        },
      ],
    },
  },
];
